version: '3'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    networks:
      - main
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/custom.conf:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped

  nginx-proxy-acme:
    image: jrcs/letsencrypt-nginx-proxy-companion
    networks:
      - main
    depends_on:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    restart: unless-stopped

  app:
    container_name: loomio-app
    image: ${LOOMIO_CONTAINER_IMAGE}:${LOOMIO_CONTAINER_TAG}
    restart: unless-stopped
    expose:
      - 3000
    env_file: ./env
    environment:
      - DATABASE_URL=postgresql://postgres:password@db/loomio_production
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./uploads:/loomio/public/system
      - ./storage:/loomio/storage
      - ./files:/loomio/public/files
      - ./plugins:/loomio/plugins/docker
      - ./import:/import
      - ./tmp:/loomio/tmp
    networks:
      - main
    depends_on:
      - db
      - redis

  worker:
    container_name: loomio-worker
    image: ${LOOMIO_CONTAINER_IMAGE}:${LOOMIO_CONTAINER_TAG}
    restart: always
    networks:
      - main
    env_file: ./env
    environment:
      - DATABASE_URL=postgresql://postgres:password@db/loomio_production
      - REDIS_URL=redis://redis:6379
      - TASK=worker
    volumes:
      - ./uploads:/loomio/public/system
      - ./storage:/loomio/storage
      - ./files:/loomio/public/files
      - ./plugins:/loomio/plugins/docker

  db:
    container_name: loomio-db
    image: postgres:${POSTGRES_CONTAINER_TAG}
    restart: unless-stopped
    networks:
      - main
    volumes:
      - ./pgdata:/pgdata
      - ./pgdumps:/pgdumps
    environment:
     - POSTGRES_PASSWORD=password
     - POSTGRES_DB=loomio_production
     - PGDATA=/pgdata

  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    user: postgres:postgres
    volumes:
      - ./pgdumps:/backups
    links:
      - db
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=loomio_production
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_EXTRA_OPTS=-Z6 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=1
      - BACKUP_KEEP_MONTHS=1
      - HEALTHCHECK_PORT=8080

  redis:
    container_name: loomio-redis
    image: redis:5.0
    restart: unless-stopped
    networks:
      - main

  mailin:
    container_name: loomio-mailin
    image: ${MAILIN_CONTAINER_IMAGE}:${MAILIN_CONTAINER_TAG}
    restart: unless-stopped
    networks:
      - main
    ports:
      - "25:25"
    environment:
      - WEBHOOK_URL=http://app:3000/email_processor/

  channels:
    container_name: loomio-channels
    image: loomio/loomio_channel_server
    restart: unless-stopped
    networks:
      - main
    env_file: ./channels_env
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379

networks:
  main:

volumes:
  certs:
  vhost:
  html:
  acme:
